### ISSUE TITLE
Error while trying to run solution

### ISSUE THREAD

**Issue by julianagius** [BioASQ/Evaluation-Measures#1]
When trying to run the command using java 9.0.4: 
_java -Xmx10G -cp $CLASSPATH:./flat/BioASQEvaluation/dist/BioASQEvaluation.jar converters.MapMeshResults mesh/mapping.txt system_A_results.txt system_A_results_mapped.txt_

I am getting the following error:
_Error: Could not find or load main class converters.MapMeshResults
Caused by: java.lang.ClassNotFoundException: converters.MapMeshResults_

May you please assist?

**Comment by eirinivand** [comment]
I believe `$CLASSPATH:` is not needed, consider trying the following: 
`java -Xmx10G -cp ./flat/BioASQEvaluation/dist/BioASQEvaluation.jar converters.MapMeshResults mesh/mapping.txt system_A_results.txt system_A_results_mapped.txt`

Please let us know if that was the problem :)

**Comment by julianagius** [comment]
Yes that solved this issue. Thank you for your prompt response.
